### ISSUE TITLE
Complex CQL Queries

### ISSUE THREAD

**Issue by liamjack** [lesstif/confluence-rest-api#4]
How could you use the API Client in it's current state to perform more complex CQL Queries such as:

    (type=page and space=DEV) OR (creator=admin and type=blogpost) 

Because as I understand correctly the only queries currently possible with CQLService are simple like:

    $s = new CQLService();

    $ret = $s->search([
        'SPACE' => 'LAR',
        'type' => 'page',
    ]);

which would translate to:

    SPACE=LAR AND type=page

**Comment by lesstif** [comment]
sorry, this repository was personal purpose only, i'm no longer use CQL and this API client.

so I can't answer your question because I don't know much.

**Comment by liamjack** [comment]
Ok, thanks for your reply
